# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release

sudo: required
cache: packages

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended 
# texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

# code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
