# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

sudo: false
cache: packages

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

# code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
